spring.application.name=alumnos
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.hcduoyffjllhofzkhnju
spring.datasource.password=4YvV3k.rt6=?

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.config.import=optional:application-local.properties

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
